- name: Copy .bashrc to /home
  copy:
    src: "{{ item }}"
    dest: "/home/vagrant/{{ item }}"
    mode: 0777
    owner: vagrant
    group: vagrant
  with_items:
    - .bashrc
    - .bash_profile

- name: Copy provision-debian-opencv.sh to /home
  copy:
    src: provision-debian-opencv.sh
    dest: /home/vagrant/provision-debian-opencv.sh
    mode: 0777
    owner: vagrant
    group: vagrant

- name: Run shell provision script
  shell: "/home/vagrant/provision-debian-opencv.sh > provision-debian-opencv.sh.out"
