
- name: Add armhf arch
  shell: sudo dpkg --add-architecture armhf
  become: yes

- name: Install opencv packages
  become: yes
  apt:
    name: "{{ packagesdep }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  vars:
    packagesdep:
      - qemu-user-static
      - build-essential 
      - cmake 
      - git
      - pkg-config
      - unzip 
      - libjpeg-dev:armhf
      - libpng-dev:armhf
      - libtiff-dev:armhf
      - libavcodec-dev:armhf
      - libavformat-dev:armhf
      - libswscale-dev:armhf
      - libv4l-dev:armhf
      - libxvidcore-dev:armhf
      - libx264-dev:armhf
      - libxkbcommon-dev:armhf
      - libgtk2.0-dev:armhf
      - libgtk-3-dev:armhf
      - libcanberra-gtk*
      - libcanberra-gtk-dev:armhf
      - libatlas-base-dev 
      - zlib1g-dev:armhf
      - gfortran
      - python3-dev
      - python3-numpy
      - python-dev
      - python-numpy
      - crossbuild-essential-armhf
      - gfortran-arm-linux-gnueabihf
  

