# ansible playbook for 
# * updating the kernel
# * doing a reboot
# * installing opencv packages
# * cross compiling opencv 
---
- hosts: all
  gather_facts: no
  roles:
    - vagrant
  become: yes

- hosts: all
  gather_facts: no
  roles:
    - opencv
  tags:
    - opencv